const homeDir = process.env.HOME;

export const unitSourceUrls = [
  "https://cdn.jsdelivr.net/gh/yahiro07/wus-units@r3/wavicle/",
  "https://cdn.jsdelivr.net/gh/yahiro07/wus-custom-units@r7/additive/",
  "https://cdn.jsdelivr.net/gh/yahiro07/wus-custom-units@r7/drum-machine/",
  "https://cdn.jsdelivr.net/gh/yahiro07/wus-custom-units@r7/wasyn-1/",
  "https://cdn.jsdelivr.net/gh/yahiro07/wus-custom-units@r7/webaudio-tinysynth-simple/",
  "https://cdn.jsdelivr.net/gh/yahiro07/wus-custom-units@r7/bc-010/",
  "https://cdn.jsdelivr.net/gh/yahiro07/wus-custom-units@r7/koodori/",
  "https://cdn.jsdelivr.net/gh/yahiro07/wus-custom-units@r7/webaudio-synth-v2/",
  `/dev-units/mu1-instrument/`,
  `/dev-units/mu2-sequencer/`,
  `/dev-units/mu3-effect/`,
  `/dev-units/mu4-keyboard/`,
  `/dev-units/mu5-visualizer/`,
  `file://${homeDir}/wus-my-units/my-drum-machine/`,
  `file://${homeDir}/wus-my-units/proto-engine-ptm-osc/`,
  `file://${homeDir}/wus-my-units/proto-engine-pd-fm/`,
  `file://${homeDir}/wus-my-units/mini-synth/`,
  `file://${homeDir}/wus-my-units/mini-synth-ge/`,
  `file://${homeDir}/wus-my-units/mini-synth-gp/`,
  `file://${homeDir}/wus-my-units/useq/`,
  `file://${homeDir}/wus-my-units/twsq1/`,
];
